spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com"
          audiences:
            - agenda-plus-cc653
          issuer-uri: "https://securetoken.google.com/agenda-plus-cc653"
          jws-algorithms:
            - RS256
