spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/agendaplus
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
